language: c

jobs:
  - os: linux
  - os: osx
    before_install:
      - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install bison
      - export PATH="/usr/local/opt/bison/bin:$PATH"

env:
  - MRUBY_CONFIG=travis_config.rb

script:
  - rake gensym && rake -m && rake test
